### Questin 1 

In [1]:
function error(errstring)
    println(errstring)
    input = readline()
    
end


error (generic function with 1 method)

### Question 2

In [2]:
function swapRows!(A,i,j)
    if ndims(A) == 1
        A[i],A[j] = A[j],A[i]
    else
        A[i,:],A[j,:] = A[j,:],A[i,:]
    end
    return A
end

swapRows! (generic function with 1 method)

### Question 3

In [3]:
import LinearAlgebra
function gaussPivot(A::Array{Float64,2}, b::Array{Float64,1}, tol=1.0e-12)
    n = length(b)
    count = 0 # store the number of swaps
    
#     set up scale factors
    s = zeros(n)
    for i in 1:n
        s[i] = maximum(abs.(A[i,:]))
    end
    
    
    # Row interchange, if needed
    for k in 1:n-1
        
        p = argmax(abs.(A[k:n,k]) ./ s[k:n]) +k -1
     

        if abs(A[p,k]) < tol
            error("Matrix is singular")
        end
        
        if p != k
            swapRows!(b,k,p)
            swapRows!(s,k,p)
            swapRows!(A,k,p)
            count += 1
        end   
        
        # Elimination
        for i in k+1:n
            if A[i,k] != 0.0
                lam = A[i,k] / A[k,k]
                A[i,k+1:n] = A[i,k+1:n] - lam * A[k,k+1:n]
                b[i] = b[i] -lam*b[k]
            end
        end
    end
    
    if abs(A[n,n]) < tol
        error("Matrix is singular")
    end
    
#     Back substitution
    b[n] = b[n] / A[n,n]
    for k in (n-1):-1:1
        b[k] = (b[k]-LinearAlgebra.dot(A[k,k+1:n],b[k+1:n])) / A[k,k]
    end
 
    return (b,count)
end



gaussPivot (generic function with 2 methods)

### Question 4

In [4]:
A = [
    2.0 -1 0 0
    0 0 -1 1
    0 -1 2 -1
    -1 2 -1 0
]

4×4 Array{Float64,2}:
  2.0  -1.0   0.0   0.0
  0.0   0.0  -1.0   1.0
  0.0  -1.0   2.0  -1.0
 -1.0   2.0  -1.0   0.0

In [5]:
b = [ 1, 0.0, 0, 0]

4-element Array{Float64,1}:
 1.0
 0.0
 0.0
 0.0

### Question 5

In [6]:
A \ b

4-element Array{Float64,1}:
 0.9999999999999998
 0.9999999999999996
 0.9999999999999993
 0.9999999999999993

### Question 6

In [7]:
x,count = gaussPivot(A,b)
println("the solution is : $x")
println("the number of swaps is : $count")

the solution is : [0.9999999999999998, 0.9999999999999997, 0.9999999999999996, 0.9999999999999996]
the number of swaps is : 2


### Question 7

In [8]:
@timev matrix_A = rand(1000,1000)

  0.049295 seconds (124.24 k allocations: 14.157 MiB)
elapsed time (ns): 49294555
bytes allocated:   14844444
pool allocs:       124226
non-pool GC allocs:15
malloc() calls:    1


1000×1000 Array{Float64,2}:
 0.217993   0.31677    0.159115   …  0.712029   0.164602   0.689182 
 0.0365016  0.164039   0.130356      0.833636   0.389361   0.70207  
 0.243044   0.6512     0.55719       0.260049   0.983523   0.610551 
 0.456812   0.339328   0.298569      0.301008   0.432999   0.199522 
 0.867384   0.408576   0.181766      0.394082   0.866847   0.274603 
 0.722424   0.0668732  0.859959   …  0.0221969  0.233236   0.731766 
 0.877079   0.154225   0.352027      0.547146   0.0564434  0.747418 
 0.206799   0.838149   0.224823      0.132909   0.59389    0.174706 
 0.115386   0.802714   0.0720457     0.372408   0.130464   0.192096 
 0.891143   0.39656    0.0935458     0.0900841  0.639369   0.707635 
 0.649797   0.831287   0.571729   …  0.0828038  0.358765   0.650422 
 0.150044   0.511378   0.341953      0.244902   0.162133   0.239151 
 0.973609   0.183368   0.925216      0.706497   0.0514108  0.725805 
 ⋮                                ⋱                                 
 0.540

### Question 8

In [9]:
@timev  vector_b = randn(1000)

  0.068381 seconds (162.36 k allocations: 8.790 MiB, 12.49% gc time)
elapsed time (ns): 68381331
gc time (ns):      8541805
bytes allocated:   9217461
pool allocs:       162348
non-pool GC allocs:14
GC pauses:         1


1000-element Array{Float64,1}:
 -0.17172331423426715
  0.5795174254345192 
  0.43722259254259505
 -0.547610524930869  
 -0.3593463385425568 
 -0.5719231675827015 
 -0.7149524936747942 
  0.1855454841447672 
 -0.7295867624714004 
  1.0459532681609414 
  1.0562430875123119 
 -1.4558394531793755 
 -1.9633486678171619 
  ⋮                  
 -0.2855351701375168 
 -0.9843953874054311 
 -1.2108946734008805 
 -0.6876659457150774 
 -0.44523158162164955
  1.1573256570701556 
  1.098210089667356  
  1.3833182740737597 
 -0.3767894268546188 
  1.0287985282745329 
 -0.6521257868487275 
  0.6787628703611118 

### Question 9

In [10]:
@timev x1= matrix_A \ vector_b
x1

  0.030407 seconds (10 allocations: 7.645 MiB)
elapsed time (ns): 30407084
bytes allocated:   8016576
pool allocs:       7
non-pool GC allocs:2
malloc() calls:    1


1000-element Array{Float64,1}:
 -3.050776096801361  
  1.1749407126160163 
 -1.2608572127604833 
 -1.3430419796947277 
  0.9895452726842924 
  3.2067056390154356 
  0.2130749582012637 
 -1.8906207994268989 
 -0.0793012635818603 
 -0.7968312673467757 
 -0.9102994451047196 
  1.5322116343119336 
  1.2643871652241916 
  ⋮                  
  0.44397180717260154
 -1.1213443464863933 
  0.09819587729098618
 -0.7513118412427392 
  0.3702435225142161 
  1.3923247888887833 
 -0.2639101841387408 
 -1.385153743505421  
  1.2580197560269741 
 -0.3181726938581012 
  0.1416853451949697 
 -1.8762434028908606 

In [11]:
@timev x2, count2 =  gaussPivot(matrix_A,vector_b)
println("the number of swaps is: $count2")

  3.441682 seconds (2.01 M allocations: 10.257 GiB, 23.72% gc time)
elapsed time (ns): 3441681848
gc time (ns):      816320583
bytes allocated:   11013879840
pool allocs:       120788
non-pool GC allocs:1886201
GC pauses:         480
the number of swaps is: 991


In [12]:
x2

1000-element Array{Float64,1}:
 -3.050776096800459  
  1.1749407126149316 
 -1.2608572127603468 
 -1.3430419796938897 
  0.9895452726846158 
  3.2067056390142525 
  0.21307495820063516
 -1.8906207994269102 
 -0.07930126358188229
 -0.7968312673458778 
 -0.9102994451044577 
  1.5322116343112115 
  1.2643871652238845 
  ⋮                  
  0.443971807171724  
 -1.1213443464864388 
  0.09819587729166183
 -0.7513118412425159 
  0.37024352251508574
  1.3923247888890058 
 -0.2639101841390997 
 -1.385153743505555  
  1.2580197560263844 
 -0.31817269385768665
  0.1416853451951283 
 -1.8762434028906216 

## Comment: Julia's left devision is better than the gaussPivot()

### Question 11

In [ ]:
@timev matrix_2 = rand(1000000, 1000000)

### comment:  I tried this question, but it would take a long time to finish, thus I interrupted the compile. my computer can't handle the matrix with the dimension of 1000000 .

### Question 12

### I think the largest matrix my computer can handle is about 1000000 rows and columns