### Question 1.  define a Julia function generatevectorlist(n, k) : making a list (array) of n vectors each of which is of length k.

In [9]:
using Pkg
Pkg.add("Distributions")


  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
Fetching: [========================================>]  99.9 %0.0 %12.1 %==========>                              ]  24.3 %]  36.3 %====================>                    ]  48.4 %>             ]  66.4 %================================>        ]  78.5 %90.5 %Fetching: [=======================================> ]  96.0 % Resolving package versions...
 Installed Mocking ─────────── v0.7.0
 Installed PDMats ──────────── v0.9.10
 Installed FillArrays ──────── v0.7.0
 Installed Parameters ──────── v0.12.0
 Installed CategoricalArrays ─ v0.6.0
 Installed DataFrames ──────── v0.19.4
 Installed TimeZones ───────── v0.10.0
 Installed Widgets ─────────── v0.6.2
 Installed Optim ───────────── v0.19.3
 Installed CSV ─────────────── v0.5.12
  Updating `~/.julia/environments/v1.2/Project.toml`
  [31c24e10] + Distributions v0.19.2
  Updating `~/.julia/environments/v1.2/Manifest.to

In [10]:
using Distributions

┌ Info: Precompiling Distributions [31c24e10-a181-5473-b8eb-7969acd0382f]
└ @ Base loading.jl:1242
┌ Warning: `lgamma(x::Real)` is deprecated, use `(logabsgamma(x))[1]` instead.
│   caller = lstirling_asym(::BigFloat) at misc.jl:56
└ @ StatsFuns ~/.julia/packages/StatsFuns/2QE7p/src/misc.jl:56


In [11]:
function generatevectorlist(n::Int64, k::Int64)
    
    ls = []
    for _ in 1:n
        ls = append!(ls, [rand(Normal(0,1),k)])
    end
    ls
end

generatevectorlist (generic function with 1 method)

### Question 2: A cell with the function call that makes a list x of 5 vectors each of length 3:

In [12]:
x = generatevectorlist(5,3)

5-element Array{Any,1}:
 [-1.5187206244445282, 0.5793434382951507, 1.3579668005041339] 
 [0.005936397284809032, 0.7003155685199485, 0.7331415220233969]
 [-0.4151905885344155, 1.2693614033489857, 0.9664540223444359] 
 [0.880394769842293, -0.5486840723429499, 0.9324001299376656]  
 [-0.2901425675236978, 1.134747283703641, 1.151408264694852]   

### Question 3 : A cell containing the definition of a second method for the generatevectorlist function.

In [13]:
generatevectorlist() = generatevectorlist(10,4)

generatevectorlist (generic function with 2 methods)

### Question 4 : A cell with the function call generatevectorlist()

In [14]:
generatevectorlist()

10-element Array{Any,1}:
 [-1.6770184317300063, -0.7438847742438816, -2.4244636038126757, 1.2537046640093006]  
 [1.353778827070885, 0.1603559575723369, 1.0486170673892719, 0.40345643474690224]     
 [-0.2693889067587757, 0.08585439887870286, 1.2445711690644063, 0.7235369819712812]   
 [-1.7226079573951765, -0.061210136678212484, 2.369971379828042, -0.08935038626145769]
 [-1.3568685011168748, -2.4230728947847138, -1.1966259019142755, 1.087940863446087]   
 [-1.385651048880047, -0.29846318122088294, 0.09621551743245721, 0.6984531736254221]  
 [-1.2891259580802075, 0.03357062342015867, 1.774804920879201, -0.6614236971826264]   
 [-1.111942956031147, 0.5285451667096547, -1.2665209403086217, -1.1092836820053364]   
 [1.28886026907558, -1.9357040313777665, 1.4822441730401357, -0.8866183477355779]     
 [0.253156711483983, -0.050926650088072144, -0.5386687825434222, 2.509894768062255]   

### Question 5 : A cell containing the definition of a third method for the generatevectorlist function

In [15]:
generatevectorlist(n) = generatevectorlist(n, 5)

generatevectorlist (generic function with 3 methods)

### Question 6 : A cell with the function call generatevectorlist(100)

In [16]:
generatevectorlist(100)

100-element Array{Any,1}:
 [0.07188079076768437, 0.27031952719729463, 2.086497881688037, 0.8950943992067418, -0.8284201048157297]     
 [0.9051131454797043, -0.40070882780666967, -1.8235587118496424, -0.02720637793883278, -2.0694939876424088] 
 [-0.3817203412105527, 0.41279609133847756, 0.5012924039252051, -1.198994764785284, -0.06534360439339441]   
 [0.9533802767108546, -0.8617666461370748, -0.64758004727929, -0.04823261229717292, -0.7844960167370533]    
 [0.07413717420862936, 1.69977372681097, -0.4296357998157008, 0.40184760186989715, -0.5990402127403252]     
 [-1.5188257152366178, -0.08563315667435445, -0.10235590670491536, -0.07317325181123953, 0.8612397299733582]
 [0.5724385486333265, -0.0007421226819572462, -0.3128297203928617, -0.7744931257378295, 1.130666517901937]  
 [0.6480860894568, 1.1905273500417581, -0.9256519624208328, 0.8708488863823467, -1.0792485967869019]        
 [-2.2079945455800147, 0.21045725825594067, -0.13900297340029197, 0.30270999128406645, -0.757692674090

### Question 7 : A cell containing the definition of a Julia function combinelinearly(scales, vectors)

In [29]:
function combinelinearly(scales::Array{Float64,1}, vectors::Array{Any,1})

    @assert length(scales) == length(vectors) "scales and vectors are supposedly of the same length"
    res = zeros(length(vectors[1]))
    for i in 1:length(scales)
        res += scales[i] * vectors[i]
    end
    return res
end
     

combinelinearly (generic function with 3 methods)

### Question 8 : A cell that makes a list z of 5 numbers randomly but uniformly distributed between 0 and 1.

In [22]:
z = rand(5)

5-element Array{Float64,1}:
 0.8038515322875612 
 0.570998702837886  
 0.38547108929423124
 0.15275171165576462
 0.6939547367095582 

### Question 9 : A cell that calls combinelinearly on z and x, of 8. and 2. above.

In [19]:
combinelinearly(z, x)

3-element Array{Float64,1}:
 -0.5321765608248795
  1.5075322088752978
  2.5184930254672944

### Question 10 : A cell that shows the time for calling combinelinearly on 10,000,000 (ten million) random numbers, and 10,000,000 random vectors, each of length 50, obtained by generatevectorlist.

In [40]:
@time combinelinearly(rand(10_000_000), generatevectorlist(10_000_000, 5))

  7.489644 seconds (50.02 M allocations: 4.821 GiB, 44.29% gc time)


5-element Array{Float64,1}:
 -2462.716233440828 
  2816.055198898732 
 -3789.835975896985 
   956.4797463587746
  2694.4492886602675

### Question 11 : A cell containing the definition of a Julia function combinelinearlyshort(scales, vectors)

In [44]:
function combinelinearlyshort(scales::Array{Float64,1}, vectors::Array{Any,1})
    @assert length(scales) == length(vectors) "scales and vectors are supposedly of the same length"
    sum(scales .* vectors)
end

combinelinearlyshort (generic function with 1 method)

### Question 12 : A cell that shows the time for calling combinelinearlyshort on 10,000,000 (ten million) random numbers, and 10,000,000 random vectors, each of length 50, obtained by generatevectorlist. Just one line in this cell. Which seems to be faster, combinelinearly or combinelinearlyshort?

In [45]:
@time combinelinearlyshort(rand(10_000_000), generatevectorlist(10_000_000, 5))

  9.006511 seconds (60.71 M allocations: 5.080 GiB, 57.69% gc time)


5-element Array{Float64,1}:
  1329.4794346851736 
    98.87897568065796
   917.5944057678262 
 -2064.687718062536  
  3499.162093483321  

### Summary: the first method with for loop seems to be faster